import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Providers from "@/providers/provider";
import getAbout from "@/data/about";
import getSocialLinks from "@/data/social-links";
import getFooterLinks from "@/data/footer-links";
import MandatoryDetails from "@/components/mandatoryDetails";
import HorizontalRule from "@/components/HorizontalRule";
import ScrollToTop from "@/components/ScrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [about, socialLinks, footerLinks] = await Promise.all([
    getAbout(),
    getSocialLinks(),
    getFooterLinks(),
  ])
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiase`}
      >
        <Providers>
          <Header />
          {children}
          <ScrollToTop />
          <HorizontalRule />
          <Footer
            about={about}
            socialLinks={socialLinks}
            footerLinks={footerLinks}
          />
          <HorizontalRule />
          <MandatoryDetails about={about} />
        </Providers>
      </body>
    </html>
  );
}
